"""Generate the indicator twin of every Pine strategy in this folder.

Two scripts per hypothesis, from one source of truth. The `strategy()` version
is what you check against our backtests in the Strategy Tester; the `indicator()`
version is what you actually leave on a chart - it draws the same levels, marks
the same entries and fires alerts, and it can sit on top of another strategy
without TradingView refusing to load two strategies at once.

THE TRANSFORM, stated so it can be checked:

  1. `strategy(...)` becomes `indicator(...)`, keeping the title and `overlay`.
     Everything else in that call is position sizing and commission, which an
     indicator has no use for.
  2. Every top-level statement that touches `strategy.` is removed whole - the
     entry blocks, the exits, the position-size guards. Anything that does not
     touch it is kept verbatim, so the levels, the filters and the signal
     expressions are byte-identical to the strategy's.
  3. Rule 2 would also drop any `:=` assignment that happened to live inside one
     of those blocks. That is a silent behaviour change, so the generator
     REFUSES to write a file when it finds one unless the spec below restores it
     explicitly. ORB is the only case: it sets `taken := true` inside the entry
     block to enforce one trade per session.
  4. A marker and alert section is appended, built from the signal expressions
     named per script below. Those names are the only hand-written part; they
     are asserted to exist in the output.

Run: .venv/bin/python pine/build_indicators.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# The entry conditions, named exactly as the strategy computes them. These are
# read off the `if ... strategy.entry(...)` lines of each script; the assertions
# below fail if a name stops existing.
SPECS = {
    "vwap":       {"long": "canTrade and longSig",
                   "short": "canTrade and shortSig"},
    "ema_vwap":   {"long": "canTrade and crossUp",
                   "short": "canTrade and crossDn"},
    "orb":        {"long": "upBrk", "short": "dnBrk",
                   # the entry block set this; without it `oneTrade` stops working
                   "restore": ["if upBrk or dnBrk", "    taken := true"]},
    "sweep_fade": {"long": "canTrade and sweptLow",
                   "short": "canTrade and sweptHigh"},
    "resid":      {"long": "ready and z <= -zThr",
                   "short": "ready and z >= zThr"},
    "xsec":       {"long": "ready and isTop",
                   "short": 'ready and isBot and mode == "spread"'},
}

MARKERS = '''
// ------------------------------------------------------- signals & alerts ---
// The same two conditions the strategy enters on, drawn instead of traded.
longSignal_  = {long}
shortSignal_ = {short}
plotshape(longSignal_,  "Long signal",  shape.triangleup,   location.belowbar,
     color.new(color.green, 0), size=size.small)
plotshape(shortSignal_, "Short signal", shape.triangledown, location.abovebar,
     color.new(color.red, 0),   size=size.small)
alertcondition(longSignal_,  "{title} long",  "{title}: long signal on {{{{ticker}}}} {{{{interval}}}}")
alertcondition(shortSignal_, "{title} short", "{title}: short signal on {{{{ticker}}}} {{{{interval}}}}")
'''

ALERTS_ONLY = '''
// ------------------------------------------------------------------ alerts ---
// The markers above already draw these two conditions, so only the alerts are
// added here.
alertcondition({long},  "{title} long",  "{title}: long signal on {{{{ticker}}}} {{{{interval}}}}")
alertcondition({short}, "{title} short", "{title}: short signal on {{{{ticker}}}} {{{{interval}}}}")
'''

NOTE = '''//
// THIS IS THE INDICATOR TWIN, generated by pine/build_indicators.py from the
// strategy of the same name. Identical levels, filters and entry conditions;
// no orders, no exits, no Strategy Tester numbers. Use the strategy version
// when you want to check our backtest, this one when you want it on a chart.
// Exits are part of the edge and they are NOT shown here - a chart full of
// entry arrows says nothing about what happens after the entry.
'''


def statements(lines: list[str]) -> list[list[str]]:
    """Group lines into top-level statements: an unindented line plus the
    indented block under it."""
    out: list[list[str]] = []
    for ln in lines:
        if ln[:1] not in (" ", "\t") and (out and ln.strip() or not out):
            out.append([ln])
        elif out:
            out[-1].append(ln)
        else:
            out.append([ln])
    return out


def convert(sid: str, src: str) -> str:
    spec = SPECS[sid]
    lines = src.split("\n")

    # 1. the declaration
    i = next(k for k, ln in enumerate(lines) if ln.startswith("strategy("))
    j = i
    depth = 0
    while True:
        depth += lines[j].count("(") - lines[j].count(")")
        if depth <= 0:
            break
        j += 1
    decl = "\n".join(lines[i:j + 1])
    title = re.search(r'strategy\(\s*"([^"]+)"', decl).group(1)
    overlay = "true" if re.search(r"overlay\s*=\s*true", decl) else "false"
    ind_title = title.replace(" · prop_lab", " · signals · prop_lab")
    new_decl = f'indicator("{ind_title}", overlay={overlay})'

    body = statements(lines[:i] + [new_decl] + lines[j + 1:])

    # 2. drop every statement that touches strategy.*
    kept, dropped = [], []
    for st in body:
        (dropped if any("strategy." in ln for ln in st) else kept).append(st)
    if not dropped:
        sys.exit(f"{sid}: nothing to strip - is this already an indicator?")

    # 3. refuse to silently lose state
    lost = [ln.strip() for st in dropped for ln in st
            if ":=" in ln and "strategy." not in ln]
    restored = spec.get("restore", [])
    if lost and not restored:
        sys.exit(f"{sid}: dropped state assignments with no restore in SPECS: {lost}")

    out = "\n".join("\n".join(st) for st in kept)
    if restored:
        out = out.rstrip("\n") + "\n\n" + "\n".join(restored) + "\n"

    # 4. the note goes right under the header comment block
    out = out.replace(new_decl, NOTE + new_decl, 1)
    # H-005 already plots exactly these two conditions as sweep markers; adding
    # a second triangle on the same bar would look like two signals, not one.
    already = f'plotshape({spec["long"]}' in out and f'plotshape({spec["short"]}' in out
    if not already:
        out = out.rstrip("\n") + "\n" + MARKERS.format(
            long=spec["long"], short=spec["short"], title=title.split(" ·")[0])
    else:
        out = out.rstrip("\n") + "\n" + ALERTS_ONLY.format(
            long=spec["long"], short=spec["short"], title=title.split(" ·")[0])

    # 5. it has to actually be an indicator, and the names have to exist
    assert "strategy." not in out, f"{sid}: strategy. survived the transform"
    for expr in (spec["long"], spec["short"]):
        for name in re.findall(r"\b[a-zA-Z_]\w*\b", expr):
            if name in ("and", "or", "not"):
                continue
            assert re.search(rf"\b{name}\b", "\n".join(
                l for st in kept for l in st)), f"{sid}: {name} is not defined"
    return out


def main():
    for sid in sorted(SPECS):
        src = (HERE / f"{sid}.pine").read_text()
        out = convert(sid, src)
        dst = HERE / f"{sid}_indicator.pine"
        dst.write_text(out)
        print(f"  wrote {dst.name}  ({len(out.splitlines())} lines from "
              f"{len(src.splitlines())})")


if __name__ == "__main__":
    main()
