"""The strategy board: one page, every hypothesis, one 0-10 score each.

Answering "do we need a database": no. Every number here already lives in a file
on disk that git versions and a clone reproduces. This script reads one
`backtests/<id>/board.json` per hypothesis and writes one manifest plus one
page. A database would add a service to run, a schema to migrate and a backup to
worry about, and would buy nothing until there are enough strategies that you
want to query across individual trades rather than read summaries. At that point
the answer is a single SQLite file, not a server.

**Adding a hypothesis is one call.** Give `core.board.write_board` a stitched
walk-forward trade series and it produces the board record - prop simulation,
full risk ladder, mandatory fields, all identical to what is already here. This
script then picks it up automatically; there is nothing per-strategy in this
file. See `strategies/ribbon/stage10_board.py` for the shortest example.

Run: .venv/bin/python core/build_scoreboard.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from core import fingerprint as FP  # noqa: E402
from core.scorecard import compute, expected_days, WEIGHTS, PHASE_DAYS  # noqa: E402
from core.prop_rules import ONE_STEP, TWO_STEP  # noqa: E402
from core.riskladder import RISK_LADDER, MAX_BREACH, DD_CAP, MAX_DAYS  # noqa: E402

BT = ROOT / "backtests"
PINE = ROOT / "pine"

LADDER_NOTE = (
    "Risk per trade is the only lever left once the configuration is chosen blind, "
    "and it moves speed and survival in opposite directions. <strong>Click any "
    "row</strong> to score the strategy at that risk level. The recommended row is "
    "the fewest expected days to a funded account among the levels that keep the "
    "breach rate under 5% <em>and</em> the drawdown inside the 8% cap. Days and "
    "pass rates are the <strong>two-step</strong> evaluation (8% then 5%); the "
    "single-step number is in the last column for comparison only."
)


def _risk_row(x: dict, base: dict, fields: dict, pf_2x) -> dict:
    """One risk level, scored end to end.

    Profit factor, Sharpe and the R-multiples are scale-invariant, so only the
    risk-dependent inputs change: how many accounts pass, how many are killed by
    each cap, how fast the passers get there, and how deep the drawdown runs in
    percent."""
    m = dict(base)
    m.update(median_days_pass=x["median_days"], pass_rate=x["pass_rate"],
             fail_max=x["fail_max"], fail_daily=x["fail_daily"], max_dd=x["max_dd"])
    card = compute(m).as_dict()
    return {
        **x,
        "score": card["total"], "verdict": card["verdict"],
        "components": card["components"], "evidence_capped": card["evidence_capped"],
        "headline": {
            "pf": fields["pf"], "pf2x": pf_2x,
            "tpd": fields["trades_per_day"], "trades": fields["trades"],
            "n_books": fields.get("n_books", 1),
            "tpd_per_book": fields.get("tpd_per_book", fields["trades_per_day"]),
            "r_per_day": fields.get("r_per_day"),
            "max_dd": x["max_dd"], "pass_rate": x["pass_rate"],
            "fail_max": x["fail_max"], "fail_daily": x["fail_daily"],
            "median_days": x["median_days"], "still_open": x["still_open"],
            "expected_days": x["expected_days"],
            "expected_days_one_step": (x.get("one_step") or {}).get("expected_days"),
        },
    }


def _pine(sid: str, kind: str = "") -> str | None:
    """A TradingView port of this hypothesis, if one exists.

    Two per hypothesis: the `strategy()` version, which gives Strategy Tester
    numbers you can check against our backtests, and the `indicator()` twin
    generated by `pine/build_indicators.py`, which draws the same levels and
    signals and is what you would actually leave on a chart. Both are embedded
    in the page rather than fetched, because the board is published as a single
    self-contained artifact with no origin to fetch from."""
    p = PINE / f"{sid}{kind}.pine"
    return p.read_text() if p.exists() else None


def _declared_costs(sid: str):
    """The cost assumption the strategy declares TODAY, from its manifest. A
    record scored at 1.83bps is not a record scored at 3.00, and the manifest is
    where that number now lives - so a change to it has to invalidate the card
    the same way a kernel edit does."""
    try:
        mod = __import__(f"strategies.{sid}.manifest", fromlist=["MANIFEST"])
    except Exception:                                        # noqa: BLE001
        return None                                          # no manifest yet
    return mod.MANIFEST.get("costs")


def _fp_summary(fp: dict | None) -> dict | None:
    """The small, human-readable part of the fingerprint. The full hash map is
    kept in board.json; the page only needs enough to say what it was built on."""
    if not fp:
        return None
    return {
        "git": (fp.get("git") or {}).get("short"),
        "dirty": (fp.get("git") or {}).get("dirty"),
        "written": fp.get("written"),
        "kernel_hash": (fp.get("kernel_hash") or "")[:12],
        "kernels": sorted(fp.get("kernels") or {}),
        "costs": fp.get("costs"),
        "data": {k: {"rows": v.get("rows"), "first": v.get("first"),
                     "last": v.get("last")}
                 for k, v in (fp.get("data") or {}).items()},
    }


def load(sid: str) -> dict | None:
    p = BT / sid / "board.json"
    if not p.exists():
        return None
    b = json.loads(p.read_text())
    pick, fields = b["pick"], b["fields"]

    # Item 1: rehash what this record says it was built from, and compare with
    # what is on disk now. Nobody has to remember to mark a record superseded.
    fp = b.get("fingerprint")
    stale = FP.check(fp)
    if fp and FP.costs_changed(fp, _declared_costs(sid)):
        stale["stale"] = True
        stale["state"] = "stale"
        stale["reasons"] = list(stale["reasons"]) + ["cost assumption changed"]
        stale["detail"] = "; ".join(stale["reasons"])

    measured = dict(b["measured"])
    measured.update(median_days_pass=pick["median_days"], pass_rate=pick["pass_rate"],
                    fail_max=pick["fail_max"], fail_daily=pick["fail_daily"],
                    max_dd=pick["max_dd"],
                    stale=stale["stale"])
    card = compute(measured).as_dict()

    return {
        "id": b["id"], "hid": b["hid"], "name": b["name"], "tagline": b["tagline"],
        "period": b["period"], "report": b["report"],
        "candidate": f'{b["candidate"]}, {pick["risk"]*100:.2f}% risk per trade',
        "measured": measured, "score": card, "note": b.get("note"),
        # rendered as a badge on the card; see core/scoreboard_template.html
        "stale": stale,
        "fingerprint": _fp_summary(fp),
        "headline": {
            "pf": fields["pf"], "pf2x": b.get("pf_2x"),
            "tpd": fields["trades_per_day"], "trades": fields["trades"],
            "n_books": fields.get("n_books", 1),
            "tpd_per_book": fields.get("tpd_per_book", fields["trades_per_day"]),
            "r_per_day": fields.get("r_per_day"),
            "max_dd": pick["max_dd"], "pass_rate": pick["pass_rate"],
            "fail_max": pick["fail_max"], "fail_daily": pick["fail_daily"],
            "median_days": pick["median_days"], "still_open": pick["still_open"],
            "expected_days": expected_days(pick["median_days"], pick["pass_rate"]),
            "expected_days_one_step": (pick.get("one_step") or {}).get("expected_days"),
        },
        "ladder": {
            "picked": pick["risk"], "note": LADDER_NOTE,
            # Every row carries its own fully-computed scorecard. The page never
            # scores anything: duplicating the rubric in JavaScript would let the
            # page and core/scorecard.py drift apart silently.
            "rows": [_risk_row(x, b["measured"], fields, b.get("pf_2x"))
                     for x in b["ladder"]],
        },
        "grid": b.get("grid") or {}, "todo": b.get("todo") or [],
        # per-leg trades, when the book is more than one market: the page uses
        # them to recompute every number from whatever subset is ticked
        "legs": b.get("legs"),
        "markets": b.get("markets"),
        # pine/<id>.pine and pine/<id>_indicator.pine, shipped inline so the
        # page's copy buttons need no fetch
        "pine": _pine(sid),
        "pine_indicator": _pine(sid, "_indicator"),
    }


def _phase(r) -> dict:
    return {"target": r.profit_target, "daily": r.daily_loss,
            "maxloss": r.max_loss, "mindays": r.min_trading_days}


def main():
    ids = sorted(p.parent.name for p in BT.glob("*/board.json"))
    out = []
    for sid in ids:
        s = load(sid)
        if s:
            out.append(s)
        else:
            print(f"  skip {sid}: unreadable board.json")
    if not out:
        print("no board.json anywhere - run each strategy's board stage first")
        return
    out.sort(key=lambda s: -s["score"]["total"])

    # The evaluation rules, shipped to the page rather than restated in
    # JavaScript, so the interactive book picker simulates exactly what
    # core/riskladder.py simulates and the two cannot drift apart.
    prop = {
        "one_step": [_phase(x) for x in ONE_STEP],
        "two_step": [_phase(x) for x in TWO_STEP],
        "risk_ladder": list(RISK_LADDER), "max_breach": MAX_BREACH,
        "dd_cap": DD_CAP, "max_days": MAX_DAYS,
    }
    data = {"strategies": out, "weights": WEIGHTS, "phase_days": PHASE_DAYS,
            "prop": prop}
    (BT / "scoreboard_data.json").write_text(json.dumps(data, indent=1))
    tpl = (ROOT / "core" / "scoreboard_template.html").read_text()
    (BT / "scoreboard.html").write_text(tpl.replace("/*__DATA__*/", json.dumps(data)))

    print("wrote backtests/scoreboard.html")
    for s in out:
        pine = ("strategy+indicator" if s.get("pine") and s.get("pine_indicator")
                else "strategy only" if s.get("pine") else "NO PINE")
        st = (s.get("stale") or {}).get("state", "?")
        tag = {"ok": "", "note": "  NOTE", "stale": "  STALE",
               "unfingerprinted": "  UNFINGERPRINTED"}.get(st, "")
        print(f"  {s['hid']} {s['name']:26s} {s['score']['total']:4.1f}/10  "
              f"{s['score']['verdict']:52s} {pine}{tag}")
        if (s.get("stale") or {}).get("detail"):
            print(f"      {s['stale']['detail']}")


if __name__ == "__main__":
    main()
