// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/0WjlUeyu-Ichimoku-Cloud-strategy-for-gold-market/
// id: PUB;mdN5EBiABn7tGy2f0I7xR8kaEIkriKhv  kind: strategy  likes: 92
//@version=3
strategy(title="Ichimoku Cloud", shorttitle="Ichimoku", overlay=true, default_qty_type=strategy.cash, default_qty_value=100000, initial_capital=100000, currency=currency.USD)


conversionPeriods = input(9, minval=1, title="Conversion Line Periods"),
basePeriods = input(26, minval=1, title="Base Line Periods")
laggingSpan2Periods = input(52, minval=1, title="Lagging Span 2 Periods"),
displacement = input(26, minval=1, title="Displacement")

donchian(len) => avg(lowest(len), highest(len))

conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = avg(conversionLine, baseLine)
leadLine2 = donchian(laggingSpan2Periods)

plot(conversionLine, color=#0496ff, title="Conversion Line")
plot(baseLine, color=#991515, title="Base Line")
plot(close, offset = -displacement, color=#459915, title="Lagging Span")

p1 = plot(leadLine1, offset = displacement, color=green,
 title="Lead 1")
p2 = plot(leadLine2, offset = displacement, color=red, 
 title="Lead 2")
fill(p1, p2, color = leadLine1 > leadLine2 ? green : red)



maxlead = max(leadLine1, leadLine2)
minlead = min(leadLine1, leadLine2)

//rules
A = baseLine> maxlead[displacement]
B = crossover(baseLine,  maxlead[displacement])

C = baseLine< minlead[displacement]
D = crossunder(baseLine, minlead[displacement])


E = conversionLine> maxlead[displacement]
F = crossover(conversionLine, maxlead[displacement])

G = conversionLine< minlead[displacement]
H = crossunder(conversionLine, minlead[displacement])


I = close>  maxlead[2*displacement]
J = crossover(close, maxlead[2*displacement])

K = close<minlead[2*displacement]
L = crossunder(close, minlead[2*displacement])


M = close> maxlead[displacement]
N = crossover(close, maxlead[displacement])

O = close< minlead[displacement]
P = crossunder(close, minlead[displacement])


//strategies
if A 
    if E
        if M
            strategy.entry("Buy", strategy.long, when= J)
if A 
    if I
        if M
            strategy.entry("Buy", strategy.long, when= F)
if E 
    if I
        if M
            strategy.entry("Buy", strategy.long, when= B)
if A 
    if E
        if I
            strategy.entry("Buy", strategy.long, when= N)            

if C
    if G
        if O
            strategy.entry("Sell", strategy.short, when=L)
if C
    if K
        if O
            strategy.entry("Sell", strategy.short, when=H)
if G
    if K
        if O
            strategy.entry("Sell", strategy.short, when=D)
if C
    if G
        if K
            strategy.entry("Sell", strategy.short, when=P)

//EOS
