// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/06gU5i7b-Easy-to-Use-MACD-RSI-Strategy/
// id: PUB;w88SlnXY84haW498Sw3IG99mG4ttzZnC  kind: strategy  likes: 1887
//@version=2
strategy(title="MACD+RSI Strategy", overlay=false, default_qty_type=strategy.percent_of_equity, default_qty_value=100, initial_capital=5000, currency=currency.CAD)

///// Only enter long positions /////
strategy.risk.allow_entry_in(strategy.direction.long)

///// Backtest Start Date /////
startDate   = input(title="Start Date",  type=integer, defval=1,    minval=1,    maxval=31)
startMonth  = input(title="Start Month", type=integer, defval=1,    minval=1,    maxval=12)
startYear   = input(title="Start Year",  type=integer, defval=2016, minval=1800, maxval=2100)

afterStartDate = (time >= timestamp(syminfo.timezone, startYear, startMonth, startDate, 0, 0))

///// Create inputs /////
// MACD Inputs ///
fastLen = input(title="Fast Length", type=integer, defval=12)
slowLen = input(title="Slow Length", type=integer, defval=26)
sigLen  = input(title="Signal Length", type=integer, defval=9)

// RSI Inputs //
rsivalue = rsi(close, 14)

///// Get MACD values /////
[macdLine, signalLine, _] = macd(close, fastLen, slowLen, sigLen)

///// Plot MACD values and line /////
plot(series=macdLine, color=teal, linewidth=1)
plot(series=signalLine, color=orange, linewidth=1)

hline(price=0)

///// Highlight Trades /////
bgcolor(color=(crossover(macdLine, signalLine) and macdLine<0 and rsivalue<50) ? white : na, transp=50)
bgcolor(color=(crossunder(macdLine, signalLine) and macdLine>0) ? white : na, transp=50)

///// Submit orders /////
if (afterStartDate and crossover(macdLine, signalLine) and macdLine<0 and rsivalue<50)
    strategy.entry(id="BUY", long=true)
if (afterStartDate and crossunder(macdLine, signalLine) and macdLine>0)
    strategy.entry(id="SELL", long=false)