// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/5xJO5TfO/
// id: PUB;5EF0U9jJr7z15UiUA86P1Ha9SjPPidzG  kind: strategy  likes: 1101
//@version=4
strategy("MTF stochastic strategy", overlay=false, pyramiding=3, default_qty_type=strategy.percent_of_equity, default_qty_value=100, currency=currency.USD)
//
//this strategy is inspired to bobby thread in forexfactory forum
//
len = input(11, minval=1, title="Length for Main Stochastic")
smoothK = input(3, minval=1, title="SmoothK for Main Stochastic")
smoothD = input(3, minval=1, title="SmoothD for Main Stochastic")
upLine = input(80, minval=50, maxval=90, title="Upper Line Value?")
lowLine = input(20, minval=10, maxval=50, title="Lower Line Value?")
trailStep = input(50, minval=10, title="Trialing step value")


// current stochastic calculation
k = sma(stoch(close, high, low, len), smoothK)
d = sma(k, smoothD)

//mtf stochastic calculation smoothed with period
MTF_period= timeframe.period=='1'?'5':timeframe.period=='5'?'15':timeframe.period=='15'?'30':timeframe.period=='30'?'60':timeframe.period=='60'?'240':timeframe.period=='240'?'D':timeframe.period=='D'?'W':'M'
mtfK = linreg(security(syminfo.tickerid,MTF_period, sma(stoch(close, high, low, len), smoothK)),len,0)
mtfD = linreg(security(syminfo.tickerid,MTF_period, sma(k, smoothD)),len,0)

plot(k, "current TF k", color.black, style=plot.style_linebr)
plot(d, "current TF d", color.gray, style=plot.style_linebr)
plot(mtfK, "MTF TF k", color.red, style=plot.style_line)
plot(mtfD, "Multi TF d", color.green, style=plot.style_line)
hline(upLine)
hline(50)
hline(lowLine)

longCondition = crossover(mtfK, 50) and k > 50 and change(k, 1) > 0 and k > d and mtfK > mtfD
if longCondition
    strategy.entry("Lungo", strategy.long)

shortCondition = crossunder(mtfD, 50) and k < 50 and change(k, 1) < 0 and k < d and mtfK < mtfD
if shortCondition
    strategy.entry("Corto", strategy.short)

exitlong = crossunder(mtfD, upLine)
exitshort = crossover(mtfK, lowLine)

if exitlong
    strategy.exit("Esci lungo", "Lungo", trail_points=trailStep)
if exitshort
    strategy.exit("Esci corto", "Corto", trail_points=trailStep)


