// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/9morbD5t-15-Minute-Gold-Trend-Following-Strategy/
// id: PUB;v0d1rwLHjXobyApD15BLp3iWRG8DxwkJ  kind: strategy  likes: 699
//@version=3
strategy("MAster Gold Strategy", overlay = true, currency = currency.USD, commission_value = 0.02, initial_capital = 10000, pyramiding = 1)

strategy.entry("Buy", strategy.long, 1, when = close > ema(close, 182) and crossover(close, sma(close, 60)))
strategy.entry("Short", strategy.short, 1, when = low < sma(close, 182) and crossunder(close, ema(close, 60)))

c = crossover(sma(close, 60), close)
alertcondition(c, title = 'Gold Alert', message = 'Gold Alert')