// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/9JoYuVLt-PerfectStrategy/
// id: PUB;5LJDcTdJNOogLeUDbHaGa9KIFJ7TPz8Z  kind: strategy  likes: 1138
//@version=2
strategy("PerfectStrategy", overlay=true, default_qty_type = strategy.percent_of_equity, default_qty_value = 10)
 

x = ((open[1])/(close[1]))
x1 = ((open[2])/(close[2]))
x2= ((open[3])/(close[3]))
x3 = ((open[4])/(close[4]))
x4 = ((open[5])/(close[5]))
x5 = ((open[6])/(close[6]))
x6 = ((open[7])/(close[7]))
x7 = ((open[8])/(close[8]))
x8 = ((open[9])/(close[9]))

y = (x+x1+x2+x3+x4+x5+x6+x7+x8)/9
if (y < 1 )
    strategy.entry("Up", strategy.long)

if (y > 1)
    strategy.entry("Down", strategy.short)

//plot(strategy.equity, title="equity", color=red, linewidth=2, style=areabr)