// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/hXrtpUdS-Simple-Moving-Average-Strategy/
// id: PUB;2505  kind: strategy  likes: 1466

strategy(title="Mbit Moving Average",overlay=true)

length = input(520)
confirmBars = input(27)
price = close
ma = sma(price, length)

bcond = price > ma

bcount = bcond ? nz(bcount[1]) + 1 : 0

scond = price < ma

scount = scond ? nz(scount[1]) + 1 : 0

long =  scount == confirmBars

short = bcount == confirmBars


//Strategy

strategy.entry("long", strategy.long, when=long)

strategy.entry("short",strategy.short, when=short)
