// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/RmaiiptA-3-Duck-s-Trading-System-from-Babypips-com/
// id: PUB;cGh3FwyJKeE7G1ueqyBnBed3XSkzNQZL  kind: strategy  likes: 548
//@version=3
strategy("Babypips.com - 3 Duck's Trading System", overlay=true, max_bars_back=4000, default_qty_value=10000)
duck1 = sma(close, 2880)
duck2 = sma(close, 720)
duck3 = sma(close, 60)
plot(duck1, color=black, title="Duck 1")
plot(duck2, color=red, title="Duck 2")
plot(duck3, color=green, title="Duck 3")

// Stops and Profit inputs
inpTakeProfit   = input(defval = 500, title = "Take Profit", minval = 0)
inpStopLoss     = input(defval = 0, title = "Stop Loss", minval = 0)
inpTrailStop    = input(defval = 0, title = "Trailing Stop", minval = 0)
inpTrailOffset  = input(defval = 0, title = "Trailing Stop Offset", minval = 0)

// Stops and Profit Targets
useTakeProfit   = inpTakeProfit  >= 1 ? inpTakeProfit  : na
useStopLoss     = inpStopLoss    >= 1 ? inpStopLoss    : na
useTrailStop    = inpTrailStop   >= 1 ? inpTrailStop   : na
useTrailOffset  = inpTrailOffset >= 1 ? inpTrailOffset : na

//Specific Time to Trade
myspecifictradingtimes = input('0500-1600', type=session, title="My Defined Hours")

longCondition1 = time(period, myspecifictradingtimes) != 0
longCondition2 = duck2 >= duck1
longCondition3 = duck3 >= duck1 and duck2
if crossover(close, duck3) and longCondition3 and longCondition2 and longCondition1
    strategy.entry("Long", strategy.long, comment="LongEntry")

shortCondition1 = time(period, myspecifictradingtimes) != 0
shortCondition2 = duck2 <= duck1
shortCondition3 = duck3 <= duck1 and duck2
if crossunder(close, duck3) and shortCondition3 and shortCondition2 and shortCondition1
    strategy.entry("Short", strategy.short, comment="ShortEntry")

strategy.exit("Exit Long", from_entry = "Long", profit = useTakeProfit, loss = useStopLoss, trail_points = useTrailStop, trail_offset = useTrailOffset)
strategy.exit("Exit Short", from_entry = "Short", profit = useTakeProfit, loss = useStopLoss, trail_points = useTrailStop, trail_offset = useTrailOffset)