// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/wUN7ZnGM-VWAP-Bollinger-Bands/
// id: PUB;qXRKT7I3NLd3cGm65vsG0yufSM53PWHN  kind: strategy  likes: 260
//@version=5

strategy(shorttitle='VWAP-BB', 
         title='VWAP-Bollinger Bands', overlay=true, 
         default_qty_type=strategy.percent_of_equity, 
         default_qty_value=10,
         commission_type=strategy.commission.percent,
         commission_value = 0.1)

length = input.int(20, minval=1)

type = syminfo.type

bb_length = type == 'crypto' ? 30 : type == 'forex' ? 24 : 20

src = ta.vwap

mult = input.float(2.0, minval=0.001, maxval=50, title='StdDev')

basis = ta.sma(src, bb_length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, 'Offset', minval=-500, maxval=500)
plot(basis, 'Basis', color=color.new(#872323, 0), offset=offset)
p1 = plot(upper, 'Upper', color=color.new(color.teal, 0), offset=offset)
p2 = plot(lower, 'Lower', color=color.new(color.teal, 0), offset=offset)
fill(p1, p2, title='Background', color=color.new(#198787, 95))


if high > upper
    strategy.entry('Long', strategy.long)
if low < lower
    strategy.close('Long')


