// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/xQySH7CQ-Easy-to-Use-50-100-200-Day-Moving-Average-Strategy/
// id: PUB;ndmYsOuiNVgwMz9JYGDlIPT439ZmsP5a  kind: strategy  likes: 452
//@version=3
strategy(title="50/100/200 Moving Average Strategy", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100, initial_capital=10000, currency=currency.CAD)

// Only Enter Long Positions //
strategy.risk.allow_entry_in(strategy.direction.long)

// Create Inputs //
FastMA      =sma(close,50)
MediumMA    =sma(close,100)
SlowMA      =sma(close,200)

// Backtest Start Date Inputs //
startDate   = input(title="Start Date",  type=integer,   defval=1,    minval=1,    maxval=31)
startMonth  = input(title="Start Month", type=integer,   defval=1,    minval=1,    maxval=12)
startYear   = input(title="Start Year",  type=integer,   defval=2010, minval=1800, maxval=2100)

afterStartDate = (time >= timestamp(syminfo.timezone, startYear, startMonth, startDate, 0, 0))

// Submit Orders //
if (afterStartDate and crossover(FastMA, SlowMA))
    strategy.entry(id="BUY", long=true)

if (afterStartDate and crossunder(FastMA, SlowMA))
    strategy.entry(id="SELL", long=false)