// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/xiWyXhyj-Av3/
// id: PUB;c4751f9104324ae0805a26cd3e3874e4  kind: strategy  likes: 430
//@version=4
strategy("Av3",overlay=true,default_qty_type=strategy.percent_of_equity,default_qty_value=100)
TrailingStop=input(defval=500,title="Trailing Stop (pips)",minval=1)
TakeProfit=input(defval=500,title="Take Profit ($)",minval=1)
atr=atr(7)[0]
atrav=((atr(7)[1]+atr(7)[2]+atr(7)[3]+atr(7)[4]+atr(7)[5])/5)
if(atr>atrav)
    if (open>close[1])
    	strategy.order("BUY", strategy.long)
    if (open<close[1])
    	strategy.order("SELL", strategy.short)
if(atr<atrav)
    if (open<close[1])
    	strategy.order("BUY", strategy.long)
    if (open>close[1])
    	strategy.order("SELL", strategy.short)
strategy.close_all(when=strategy.openprofit>TakeProfit,alert_message="Close- TakeProfit")
strategy.exit("TrailStop",trail_points=TrailingStop,trail_offset=1,alert_message="Close- TrailStop")	