// prop_lab: fetched from TradingView 2026-10-08
// url: https://www.tradingview.com/script/zUMUafG8-Gold-trading-strategy-with-trend-follow-and-TDOW-concept/
// id: PUB;hygDRP8LICKyUNjTScWCpQ8SDzjIhPpP  kind: strategy  likes: 501
//@version=2
strategy("MACD + Stochastic + RSI by X001TK", shorttitle="MACD_Stoch_RSI_Strat", overlay=true)

// X001TK MACD + Stochastic + RSI Strategy
//
// 
// This strategy combines the special approach in stochastic and rsi
// strategy to buy once stochastic and rsi closes above center line "50" level 
// with a MACD strategy to buy when the MACD value goes above Signal line.
//
//
// This strategy goes long if the MACD goes above Signal and stochastic 
// goes above 50 level and rsi goes above 50 level.
//
// This pure strategy does not have any
// stop loss or take profit money management logic.
//
// Exit rule is simple. We close the position once MACD goes below Signal line
//
// 
// 
//
// Input
fastMAlen = input(12, minval=1, title="MACD fast moving average")
slowMAlen=input(26,minval=1, title="MACD slow moving average")
signalMACDlen = input(9,minval=1, title="MACD signal line moving average")
StochLength = input(14, minval=1, title="Stochastic Length")
switch=input(true, title="Enable MACD Bar Color?")
SL = input(defval=-700.00, title="Stop Loss in $", type=float, step=1)
TP = input(defval=500.00, title="Target Point in $", type=float, step=1)
plot(valuewhen(low>low[1] , low[1] , 1), linewidth=2, color=purple)

// MACD Calculation
MACD = ema(close, fastMAlen) - ema(close, slowMAlen)
signalMACD = ema(MACD, signalMACDlen)
delta = MACD - signalMACD
fastMA = ema(close,fastMAlen)
slowMA = ema(close,slowMAlen)

// Stochastic Calculation
smoothK = input(3, title="Smoothing of Stochastic %K ")
smoothD = input(3, title="Moving Average of Stochastic %K")
k = sma(stoch(close, high, low, StochLength), smoothK)
d = sma(k, smoothD)

//RSI Calculation
xRSI = rsi(close, 14)

// Colors
bartrendcolor = MACD > signalMACD and k > 50 and xRSI > 50? green : MACD < signalMACD and k < 50 and xRSI < 50? red : MACD < signalMACD? yellow : gray   
barcolor(switch?bartrendcolor:na)

// === STRATEGY ===
// conditions
longCond = MACD > signalMACD and k > 50 and xRSI > 50  
tdowCond = dayofweek==monday or dayofweek==wednesday or dayofweek==thursday
shortCond = MACD < signalMACD and k < 50 and xRSI < 50
ExitLongCond = MACD < signalMACD or strategy.openprofit<SL 
ExitShortCond = MACD > signalMACD or strategy.openprofit<SL

strategy.entry("long", strategy.long,  when=longCond==true and tdowCond==true)
strategy.close("long", when=ExitLongCond==true)
//strategy.entry("short", strategy.short,  when=shortCond==true)
//strategy.close("short", when=ExitShortCond==true)

// === /STRATEGY ===